id: P007968
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ77
  title: 'སྟོན་པ་སངས་རྒྱས་ཀྱི་སྐྱེས་རབས་བརྒྱད་བཅུ་པ། '
  author: ''
  volumes:
    f518cba7381c4730812a0f9682525825:
      image_group_id: I1KG13491
      title: Volume 1 of skyes rabs brgyad bcu pa/
      volume_number: 1
      total_pages: 349
      base_file: v001.txt
ebook_metadata:
  title: 'སྟོན་པ་སངས་རྒྱས་ཀྱི་སྐྱེས་རབས་བརྒྱད་བཅུ་པ། '
  author: ''
  sku: P007968
  cover: cover.jpg
  layers:
  - pagination
