id: P007968
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:52:20.492764
source_metadata:
  id: bdr:W4CZ77
  title: 'སྟོན་པ་སངས་རྒྱས་ཀྱི་སྐྱེས་རབས་བརྒྱད་བཅུ་པ། '
  author: ''
  volumes:
    f518cba7381c4730812a0f9682525825:
      image_group_id: I1KG13491
      title: Volume 1 of skyes rabs brgyad bcu pa/
      volume_number: 1
      total_pages: 349
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
