id: P007968
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ77
  title: 'སྟོན་པ་སངས་རྒྱས་ཀྱི་སྐྱེས་རབས་བརྒྱད་བཅུ་པ། '
  author: ''
  volumes:
    7062c84a324b4c4599ea7a097d8af193:
      image_group_id: I1KG13491
      title: ''
      volume_number: 1
      total_pages: 349
ebook_metadata:
  title: 'སྟོན་པ་སངས་རྒྱས་ཀྱི་སྐྱེས་རབས་བརྒྱད་བཅུ་པ། '
  author: ''
  sku: P007968
  cover: cover.jpg
  layers:
  - pagination
