id: IB77DEA74
legacy_id: P007968
ocr_import_info:
  bdrc_scan_id: W4CZ77
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T06:53:50'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:12:28.028353+00:00'
last_modified: 2022-09-04 05:12:40.024078
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ77
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ77
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྟོན་པ་སངས་རྒྱས་ཀྱི་སྐྱེས་རབས་བརྒྱད་བཅུ་པ།
  author: སློབ་དཔོན་དཔའ་བོ།
statistics:
  ocr_word_mean_confidence_index: 0.5168164665504071
  ocr_word_median_confidence_index: 0.5
quality: null
bases:
  I1KG13491:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG13491
      total_pages: 349
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG13491.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5168164665504071
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
